/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.japones.pratice.view;

import java.awt.Color;
import java.awt.font.TextAttribute;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;

import javax.swing.SwingConstants;

import com.japones.pratice.controller.Controller;
import com.japones.pratice.model.Palavra;

/**
 *
 * @author Suporte TI
 */
public class Tela_Intermediario_Converter_2 extends javax.swing.JFrame {

    /**
     * Creates new form Tela_3
     */
	private static int item_atual = 0;
	private static String contexto = "h2r";
	private static Palavra palavra;
	private static Connection conexao = Tela_Inicial.getConexao();
	private static int quantidade_treino = 35;
	private static ArrayList<Palavra> lista;
	private static ArrayList<String> sorteadas = new ArrayList<String>();
	private boolean clicou = false;
	private int max_palavras;

	public static void setContexto(String s) {
		contexto = s;

	}

    public Tela_Intermediario_Converter_2() throws SQLException {
        initComponents();
        getContentPane().setBackground(new Color(255, 170, 170));
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws SQLException 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws SQLException {
    	
    	

        jLabelPalavra = new javax.swing.JLabel("", SwingConstants.CENTER);
        jButtonOpcaoA = new javax.swing.JButton();
        jButtonOpcaoB = new javax.swing.JButton();
        jButtonOpcaoC = new javax.swing.JButton();
        jButtonOpcaoD = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jLabelProgresso = new javax.swing.JLabel();
        
        Controller controller = new Controller();
		lista = controller.gerarListaPalavra(conexao, 0);
		max_palavras = lista.size();
    	formatarContexto();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 170, 170));

        jLabelPalavra.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabelPalavra.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPalavra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonOpcaoA.setBackground(new java.awt.Color(255, 252, 255));
        jButtonOpcaoA.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 30)); // NOI18N
        jButtonOpcaoA.setForeground(new java.awt.Color(255, 155, 155));
        jButtonOpcaoA.setMaximumSize(new java.awt.Dimension(280, 50));
        jButtonOpcaoA.setMinimumSize(new java.awt.Dimension(280, 50));
        jButtonOpcaoA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonOpcaoAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonOpcaoAMouseExited(evt);
            }
        });
        jButtonOpcaoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcaoAActionPerformed(evt);
            }
        });

        jButtonOpcaoB.setBackground(new java.awt.Color(255, 252, 255));
        jButtonOpcaoB.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 30)); // NOI18N
        jButtonOpcaoB.setForeground(new java.awt.Color(255, 155, 155));
       jButtonOpcaoB.setMaximumSize(new java.awt.Dimension(280, 50));
        jButtonOpcaoB.setMinimumSize(new java.awt.Dimension(280, 50));
        jButtonOpcaoB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonOpcaoBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonOpcaoBMouseExited(evt);
            }
        });
        jButtonOpcaoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcaoBActionPerformed(evt);
            }
        });

        jButtonOpcaoC.setBackground(new java.awt.Color(255, 252, 255));
        jButtonOpcaoC.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 30)); // NOI18N
        jButtonOpcaoC.setForeground(new java.awt.Color(255, 155, 155));
      jButtonOpcaoC.setMaximumSize(new java.awt.Dimension(280, 50));
        jButtonOpcaoC.setMinimumSize(new java.awt.Dimension(280, 50));
        jButtonOpcaoC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonOpcaoCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonOpcaoCMouseExited(evt);
            }
        });
        jButtonOpcaoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcaoCActionPerformed(evt);
            }
        });

        jButtonOpcaoD.setBackground(new java.awt.Color(255, 252, 255));
        jButtonOpcaoD.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 30)); // NOI18N
        jButtonOpcaoD.setForeground(new java.awt.Color(255, 155, 155));
        jButtonOpcaoD.setMaximumSize(new java.awt.Dimension(280, 50));
        jButtonOpcaoD.setMinimumSize(new java.awt.Dimension(280, 50));
        jButtonOpcaoD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonOpcaoDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonOpcaoDMouseExited(evt);
            }
        });
        jButtonOpcaoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcaoDActionPerformed(evt);
            }
        });

        jButtonSair.setBackground(new Color(0,0,0,0));
        jButtonSair.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSair.setText("Sair");
        jButtonSair.setContentAreaFilled(false);
        jButtonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSairMouseExited(evt);
            }
        });
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonProximo.setBackground(new java.awt.Color(255, 252, 255));
        jButtonProximo.setFont(new java.awt.Font("Goudy Old Style", 2, 30)); // NOI18N
        jButtonProximo.setForeground(new java.awt.Color(255, 155, 155));
        jButtonProximo.setText("Próximo");
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonProximoActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jLabelProgresso.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelProgresso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProgresso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProgresso.setText((item_atual + 1) + "/" + quantidade_treino);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonOpcaoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPalavra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOpcaoB, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonOpcaoC, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonOpcaoD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButtonSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabelProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabelPalavra)
                .addGap(50, 50, 50)
                .addComponent(jButtonOpcaoA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOpcaoB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOpcaoC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOpcaoD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonProximo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOpcaoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcaoAActionPerformed
    	clicou = true;
    	conferirResposta(jButtonOpcaoA.getText());
    }//GEN-LAST:event_jButtonOpcaoAActionPerformed

    private void jButtonOpcaoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcaoBActionPerformed
    	clicou = true;
    	conferirResposta(jButtonOpcaoB.getText());
    }//GEN-LAST:event_jButtonOpcaoBActionPerformed

    private void jButtonOpcaoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcaoCActionPerformed
    	clicou = true;
    	conferirResposta(jButtonOpcaoC.getText());
    }//GEN-LAST:event_jButtonOpcaoCActionPerformed

    private void jButtonOpcaoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcaoDActionPerformed
    	clicou = true;
    	conferirResposta(jButtonOpcaoD.getText());
    }//GEN-LAST:event_jButtonOpcaoDActionPerformed

    private void jButtonOpcaoAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOpcaoAMouseEntered
         jButtonOpcaoA.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 35));
    }//GEN-LAST:event_jButtonOpcaoAMouseEntered

    private void jButtonOpcaoAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOpcaoAMouseExited
        jButtonOpcaoA.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 30));
    }//GEN-LAST:event_jButtonOpcaoAMouseExited

    private void jButtonOpcaoBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOpcaoBMouseEntered
         jButtonOpcaoB.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 35));
    }//GEN-LAST:event_jButtonOpcaoBMouseEntered

    private void jButtonOpcaoBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOpcaoBMouseExited
        jButtonOpcaoB.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 30));
    }//GEN-LAST:event_jButtonOpcaoBMouseExited

    private void jButtonOpcaoCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOpcaoCMouseEntered
         jButtonOpcaoC.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 35));
    }//GEN-LAST:event_jButtonOpcaoCMouseEntered

    private void jButtonOpcaoCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOpcaoCMouseExited
        jButtonOpcaoC.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 30));
    }//GEN-LAST:event_jButtonOpcaoCMouseExited

    private void jButtonOpcaoDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOpcaoDMouseEntered
        jButtonOpcaoD.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 35));
    }//GEN-LAST:event_jButtonOpcaoDMouseEntered

    private void jButtonOpcaoDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOpcaoDMouseExited
        jButtonOpcaoD.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 30));
    }//GEN-LAST:event_jButtonOpcaoDMouseExited

    private void jButtonSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseEntered
        Map<TextAttribute, Object> atributos = new HashMap<TextAttribute, Object>();
        atributos.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        jButtonSair.setFont(new java.awt.Font("Calibri", 1, 30).deriveFont(atributos));
    }//GEN-LAST:event_jButtonSairMouseEntered

    private void jButtonSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseExited
        jButtonSair.setFont(new java.awt.Font("Calibri", 0, 30));
    }//GEN-LAST:event_jButtonSairMouseExited

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        Tela_Sair_Confirma.setContexto(7);
        new Tela_Sair_Confirma().main(null);
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonProximoActionPerformed
    	if(clicou)
    	item_atual++;
		if (item_atual < quantidade_treino) {
			new Tela_Intermediario_Converter_2().main(null);
		} else {
			item_atual = 0;

			new Tela_Intermediario().main(null);

		}

		this.dispose();
    }//GEN-LAST:event_jButtonProximoActionPerformed
    
    private void formatarContexto() throws SQLException {
		Controller controller = new Controller();
		palavra = controller.sortearPalavraIntermediario(lista);
		if(sorteadas.size() == (max_palavras - 1))
			sorteadas.clear();
		while(sorteadas.contains(palavra.getRomaji()))
			palavra = controller.sortearPalavraIntermediario(lista);
		sorteadas.add(palavra.getRomaji());
		ArrayList<Palavra> opcoes = controller.gerarOpcoes(controller.gerarListaPalavra(conexao, palavra.getSilabas()), palavra);
		opcoes.add(palavra);
		jLabelPalavra.setText(palavra.getRomaji() + " (" + palavra.getPortugues() + ")");
		Random random = new Random();
		int pos = 0;
		
		switch (contexto) {

			case "r2h":
				pos = random.nextInt(opcoes.size());
				jButtonOpcaoA.setText(opcoes.get(pos).getHiragana());
				opcoes.remove(pos);
				pos = random.nextInt(opcoes.size());
				jButtonOpcaoB.setText(opcoes.get(pos).getHiragana());
				opcoes.remove(pos);
				pos = random.nextInt(opcoes.size());
				jButtonOpcaoC.setText(opcoes.get(pos).getHiragana());
				opcoes.remove(pos);
				pos = random.nextInt(opcoes.size());
				jButtonOpcaoD.setText(opcoes.get(pos).getHiragana());
				
				
				
				break;

			case "r2k":
				pos = random.nextInt(opcoes.size());
				jButtonOpcaoA.setText(opcoes.get(pos).getKatakana());
				opcoes.remove(pos);
				pos = random.nextInt(opcoes.size());
				jButtonOpcaoB.setText(opcoes.get(pos).getKatakana());
				opcoes.remove(pos);
				pos = random.nextInt(opcoes.size());
				jButtonOpcaoC.setText(opcoes.get(pos).getKatakana());
				opcoes.remove(pos);
				pos = random.nextInt(opcoes.size());
				jButtonOpcaoD.setText(opcoes.get(pos).getKatakana());
				
				

			
				break;

			default:
				break;
		}
	}
    
    public void conferirResposta(String resposta) {
    	String resposta_correta = "";
    	if(contexto.equals("r2h")) 
    		resposta_correta = palavra.getHiragana();
    	else 
    		resposta_correta = palavra.getKatakana();
    	
    		
    	if(jButtonOpcaoA.getText().equals(resposta_correta)){
			jButtonOpcaoA.setBackground(Color.green);
			jButtonOpcaoA.setForeground(Color.white);
		}else if(jButtonOpcaoB.getText().equals(resposta_correta)){
			jButtonOpcaoB.setBackground(Color.green);
			jButtonOpcaoB.setForeground(Color.white);
		}else if(jButtonOpcaoC.getText().equals(resposta_correta)){
			jButtonOpcaoC.setBackground(Color.green);
			jButtonOpcaoC.setForeground(Color.white);
		} else {
			jButtonOpcaoD.setBackground(Color.green);
			jButtonOpcaoD.setForeground(Color.white);
		}
    		if(!resposta.equals(resposta_correta)) {
    			if(jButtonOpcaoA.getText().equals(resposta)){
    				jButtonOpcaoA.setBackground(Color.red);
    				jButtonOpcaoA.setForeground(Color.white);
    			}else if(jButtonOpcaoB.getText().equals(resposta)){
    				jButtonOpcaoB.setBackground(Color.red);
    				jButtonOpcaoB.setForeground(Color.white);
    			}else if(jButtonOpcaoC.getText().equals(resposta)){
    				jButtonOpcaoC.setBackground(Color.red);
    				jButtonOpcaoC.setForeground(Color.white);
    			} else {
    				jButtonOpcaoD.setBackground(Color.red);
    				jButtonOpcaoD.setForeground(Color.white);
    			}
    					
    			
    		}
    	
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Intermediario_Converter_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Intermediario_Converter_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Intermediario_Converter_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Intermediario_Converter_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new Tela_Intermediario_Converter_2().setVisible(true);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOpcaoA;
    private javax.swing.JButton jButtonOpcaoB;
    private javax.swing.JButton jButtonOpcaoC;
    private javax.swing.JButton jButtonOpcaoD;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelPalavra;
    private javax.swing.JLabel jLabelProgresso;
    // End of variables declaration//GEN-END:variables
}
