/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.japones.pratice.view;

import java.awt.Color;
import java.awt.font.TextAttribute;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Suporte TI
 */
public class Tela_Sair_Confirma extends javax.swing.JFrame {

    /**
     * Creates new form Tela_3
     */
	
	private static int contexto = 0;
	
	
	public static void setContexto(int i) {
		contexto = i;
	}
	
    public Tela_Sair_Confirma() {
        initComponents();
        getContentPane().setBackground(new Color(255, 170, 170));
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonSim = new javax.swing.JButton();
        jButtonNao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 170, 170));

        jScrollPane1.setBackground(new Color(0,0,0,0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setOpaque(false);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 170, 170));
        jTextArea1.setColumns(2);
        jTextArea1.setFont(new java.awt.Font("Calibri", 1, 60)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(1);
        jTextArea1.setText("Tem certeza que deseja sair?");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonSim.setBackground(new java.awt.Color(255, 252, 255));
        jButtonSim.setFont(new java.awt.Font("Goudy Old Style", 2, 30)); // NOI18N
        jButtonSim.setForeground(new java.awt.Color(255, 155, 155));
        jButtonSim.setText("Sim");
        jButtonSim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSimMouseExited(evt);
            }
        });
        jButtonSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonSimActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jButtonNao.setBackground(new java.awt.Color(255, 252, 255));
        jButtonNao.setFont(new java.awt.Font("Goudy Old Style", 2, 30)); // NOI18N
        jButtonNao.setForeground(new java.awt.Color(255, 155, 155));
        jButtonNao.setText("Não");
        jButtonNao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonNaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonNaoMouseExited(evt);
            }
        });
        jButtonNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonNaoActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNao, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSim, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonSim, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNaoActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonNaoActionPerformed
     
        	
        	switch (contexto) {
				case 0:
					new Tela_Iniciante_Escolher_Treino().main(null);
					break;
					
				case 1:
					new Tela_Iniciante_Apresentar_Atividade().main(null);
					break;
					
				case 2:
					 new Tela_Iniciante_Treino_Revisao_Escrita().main(null);
					 break;
					 
				case 3:
					 new Tela_Iniciante_Treino_Revisao_Leitura().main(null);
					 break;
					 
				case 4:
					new Tela_Iniciante_Converter().main(null);
					break;
					
				case 5:
					new Tela_Intermediario().main(null);
					break;
					
				case 6:
					new Tela_Intermediario_Converter().main(null);
					break;
					
				case 7:
					new Tela_Intermediario_Converter_2().main(null);
					
				}
        
        this.dispose();
    }//GEN-LAST:event_jButtonNaoActionPerformed

    private void jButtonSimActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonSimActionPerformed
    	 if(contexto == 0 || contexto == 5)
    	new Tela_Inicial().main(null);
    	 
    	 else if(contexto == 1)
    		 new Tela_Iniciante_Escolher_Atividade().main(null);
    	 
    	 else if(contexto > 1 && contexto < 5)
    		 new Tela_Iniciante_Escolher_Exercicio().main(null);
    	 else
    		 new Tela_Intermediario().main(null);
    	
    		 
    	 this.dispose();
    }//GEN-LAST:event_jButtonSimActionPerformed

    private void jButtonSimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSimMouseEntered
       jButtonSim.setFont(new java.awt.Font("Arial", 2, 30));
    }//GEN-LAST:event_jButtonSimMouseEntered

    private void jButtonSimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSimMouseExited
        jButtonSim.setFont(new java.awt.Font("Goudy Old Style", 2, 30));
    }//GEN-LAST:event_jButtonSimMouseExited

    private void jButtonNaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNaoMouseEntered
        jButtonNao.setFont(new java.awt.Font("Arial", 2, 30));
    }//GEN-LAST:event_jButtonNaoMouseEntered

    private void jButtonNaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNaoMouseExited
       jButtonNao.setFont(new java.awt.Font("Goudy Old Style", 2, 30));
    }//GEN-LAST:event_jButtonNaoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Sair_Confirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Sair_Confirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Sair_Confirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Sair_Confirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Sair_Confirma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNao;
    private javax.swing.JButton jButtonSim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
