/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.japones.pratice.view;

import java.awt.Color;
import java.awt.font.TextAttribute;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.SwingConstants;

import com.japones.pratice.model.Caractere;

/**
 *
 * @author Suporte TI
 */
public class Tela_Iniciante_Apresentar_Escrita extends javax.swing.JFrame {

	/**
	 * Creates new form Tela_3
	 */

	private static ArrayList<Caractere> lista;
	private static int item_atual = 0;
	private static String tipo_atividade = "h";

	public static void setLista(ArrayList<Caractere> al) {
		lista = al;
	}

	

	public Tela_Iniciante_Apresentar_Escrita() {
		initComponents();
		getContentPane().setBackground(new Color(255, 170, 170));
		setExtendedState(MAXIMIZED_BOTH);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		Caractere caractere = lista.get(item_atual);
		tipo_atividade = Tela_Iniciante_Escolher_Treino.getTipoTreino();

		jButtonSair = new javax.swing.JButton();
		jLabelImagem = new javax.swing.JLabel("", SwingConstants.CENTER);
		jLabelSom = new javax.swing.JLabel(caractere.getRomaji(), SwingConstants.CENTER);
		jButtonProximo = new javax.swing.JButton();
		jButtonAnterior = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 170, 170));

		jButtonSair.setBackground(new Color(0, 0, 0, 0));
		jButtonSair.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
		jButtonSair.setForeground(new java.awt.Color(255, 255, 255));
		jButtonSair.setText("Sair");
		
		jButtonSair.setContentAreaFilled(false);
		jButtonSair.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jButtonSairMouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				jButtonSairMouseExited(evt);
			}
		});
		jButtonSair.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonSairActionPerformed(evt);
			}
		});

		String diretorio = "";

		if (tipo_atividade.equals("h"))
			diretorio = "src/Imagens/japones_hiragana/" + caractere.getHiragana_image() + ".png";
		else
			diretorio = "src/Imagens/japones_katakana/" + caractere.getKatakana_image() + ".png";
		jLabelImagem.setBackground(new java.awt.Color(255, 255, 255));
		jLabelImagem.setIcon(new javax.swing.ImageIcon(diretorio)); // NOI18N
		jLabelImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
		jLabelImagem.setMaximumSize(new java.awt.Dimension(822, 239));
		jLabelImagem.setMinimumSize(new java.awt.Dimension(100, 100));
		jLabelImagem.setName(""); // NOI18N
		jLabelImagem.setOpaque(true);
		jLabelImagem.setPreferredSize(new java.awt.Dimension(1000, 1000));

		jLabelSom.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
		jLabelSom.setForeground(new java.awt.Color(255, 255, 255));
		jLabelSom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		jButtonProximo.setBackground(new java.awt.Color(255, 252, 255));
		jButtonProximo.setFont(new java.awt.Font("Goudy Old Style", 2, 30)); // NOI18N
		jButtonProximo.setForeground(new java.awt.Color(255, 155, 155));
		jButtonProximo.setText("Próximo");
		jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonProximoActionPerformed(evt);
			}
		});

		jButtonAnterior.setBackground(new java.awt.Color(255, 252, 255));
		jButtonAnterior.setFont(new java.awt.Font("Goudy Old Style", 2, 30)); // NOI18N
		jButtonAnterior.setForeground(new java.awt.Color(255, 155, 155));
		jButtonAnterior.setText("Anterior");
		jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonAnteriorActionPerformed(evt);
			}
		});

		if (item_atual == 0) 
			jButtonAnterior.setVisible(false);
		 else
			jButtonAnterior.setVisible(true);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(100, 100, 100).addComponent(jButtonSair)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap(85, Short.MAX_VALUE)
								.addComponent(jLabelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 1079, Short.MAX_VALUE)
								.addContainerGap(85, Short.MAX_VALUE))
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabelSom, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 171,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 171,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(50, 50, 50)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(47, Short.MAX_VALUE)
						.addComponent(jLabelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
						.addGap(20, 20, 20).addComponent(jLabelSom)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(20, 20, 20).addComponent(jButtonSair).addGap(50, 50, 50)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSairActionPerformed
		item_atual = 0;
		Tela_Sair_Confirma.setContexto(1);
		new Tela_Sair_Confirma().main(null);
		this.dispose();

	}// GEN-LAST:event_jButtonSairActionPerformed

	private void jButtonSairMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButtonSairMouseEntered
		Map<TextAttribute, Object> atributos = new HashMap<TextAttribute, Object>();
		atributos.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
		jButtonSair.setFont(new java.awt.Font("Calibri", 1, 30).deriveFont(atributos));
	}// GEN-LAST:event_jButtonSairMouseEntered

	private void jButtonSairMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButtonSairMouseExited
		jButtonSair.setFont(new java.awt.Font("Calibri", 0, 30));
	}// GEN-LAST:event_jButtonSairMouseExited

	private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonProximoActionPerformed
		item_atual++;
		if (item_atual < lista.size())
			new Tela_Iniciante_Apresentar_Escrita().main(null);
		else {
			new Tela_Iniciante_Escolher_Exercicio().main(null);
			item_atual = 0;
		}
			this.dispose();
	}// GEN-LAST:event_jButtonProximoActionPerformed

	private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAnteriorActionPerformed
		item_atual--;
		new Tela_Iniciante_Apresentar_Escrita().main(null);
		this.dispose();
	}// GEN-LAST:event_jButtonAnteriorActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Tela_Iniciante_Apresentar_Escrita.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Tela_Iniciante_Apresentar_Escrita.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Tela_Iniciante_Apresentar_Escrita.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Tela_Iniciante_Apresentar_Escrita.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Tela_Iniciante_Apresentar_Escrita().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonAnterior;
	private javax.swing.JButton jButtonProximo;
	private javax.swing.JButton jButtonSair;
	private javax.swing.JLabel jLabelImagem;
	private javax.swing.JLabel jLabelSom;
	// End of variables declaration//GEN-END:variables
}
