/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.japones.pratice.view;

import java.awt.Color;
import java.awt.font.TextAttribute;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.SwingConstants;

/**
 *
 * @author Suporte TI
 */
public class Tela_Intermediario extends javax.swing.JFrame {

    /**
     * Creates new form Tela_3
     */
	
    public Tela_Intermediario() {
        initComponents();
        getContentPane().setBackground(new Color(255, 170, 170));
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel("", SwingConstants.CENTER);
        jButtonVoltar = new javax.swing.JButton();
        jButtonPalavraHiraganaRomaji = new javax.swing.JButton();
        jButtonPalavraKatakanaRomaji = new javax.swing.JButton();
        jButtonPalavraRomajiHiragana = new javax.swing.JButton();
        jButtonPalavraRomajiKatakana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 170, 170));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Treino Intermediário");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Suporte TI\\Documents\\NetBeansProjects\\JaponesPratice\\src\\Imagens\\btn_voltar.png")); // NOI18N
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonPalavraHiraganaRomaji.setBackground(new java.awt.Color(255, 252, 255));
        jButtonPalavraHiraganaRomaji.setFont(new java.awt.Font("Goudy Old Style", 2, 30)); // NOI18N
        jButtonPalavraHiraganaRomaji.setForeground(new java.awt.Color(255, 155, 155));
        jButtonPalavraHiraganaRomaji.setText("Hiragana para Romaji (Palavra)");
        jButtonPalavraHiraganaRomaji.setMaximumSize(new java.awt.Dimension(280, 50));
        jButtonPalavraHiraganaRomaji.setMinimumSize(new java.awt.Dimension(280, 50));
        jButtonPalavraHiraganaRomaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPalavraHiraganaRomajiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPalavraHiraganaRomajiMouseExited(evt);
            }
        });
        jButtonPalavraHiraganaRomaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonPalavraHiraganaRomajiActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jButtonPalavraKatakanaRomaji.setBackground(new java.awt.Color(255, 252, 255));
        jButtonPalavraKatakanaRomaji.setFont(new java.awt.Font("Goudy Old Style", 2, 30)); // NOI18N
        jButtonPalavraKatakanaRomaji.setForeground(new java.awt.Color(255, 155, 155));
        jButtonPalavraKatakanaRomaji.setText("Katakana para Romaji (Palavra)");
        jButtonPalavraKatakanaRomaji.setMaximumSize(new java.awt.Dimension(280, 50));
        jButtonPalavraKatakanaRomaji.setMinimumSize(new java.awt.Dimension(280, 50));
        jButtonPalavraKatakanaRomaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPalavraKatakanaRomajiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPalavraKatakanaRomajiMouseExited(evt);
            }
        });
        jButtonPalavraKatakanaRomaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonPalavraKatakanaRomajiActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jButtonPalavraRomajiHiragana.setBackground(new java.awt.Color(255, 252, 255));
        jButtonPalavraRomajiHiragana.setFont(new java.awt.Font("Goudy Old Style", 2, 30)); // NOI18N
        jButtonPalavraRomajiHiragana.setForeground(new java.awt.Color(255, 155, 155));
        jButtonPalavraRomajiHiragana.setText("Romaji para Hiragana (Palavra)");
        jButtonPalavraRomajiHiragana.setMaximumSize(new java.awt.Dimension(280, 50));
        jButtonPalavraRomajiHiragana.setMinimumSize(new java.awt.Dimension(280, 50));
        jButtonPalavraRomajiHiragana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPalavraRomajiHiraganaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPalavraRomajiHiraganaMouseExited(evt);
            }
        });
        jButtonPalavraRomajiHiragana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonPalavraRomajiHiraganaActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jButtonPalavraRomajiKatakana.setBackground(new java.awt.Color(255, 252, 255));
        jButtonPalavraRomajiKatakana.setFont(new java.awt.Font("Goudy Old Style", 2, 30)); // NOI18N
        jButtonPalavraRomajiKatakana.setForeground(new java.awt.Color(255, 155, 155));
        jButtonPalavraRomajiKatakana.setText("Romaji para Kataka (Palavra)");
        jButtonPalavraRomajiKatakana.setMaximumSize(new java.awt.Dimension(280, 50));
        jButtonPalavraRomajiKatakana.setMinimumSize(new java.awt.Dimension(280, 50));
        jButtonPalavraRomajiKatakana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPalavraRomajiKatakanaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPalavraRomajiKatakanaMouseExited(evt);
            }
        });
        jButtonPalavraRomajiKatakana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonPalavraRomajiKatakanaActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButtonVoltar)
                .addContainerGap(653, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPalavraHiraganaRomaji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPalavraKatakanaRomaji, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonPalavraRomajiHiragana, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonPalavraRomajiKatakana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButtonPalavraHiraganaRomaji, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPalavraKatakanaRomaji, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPalavraRomajiHiragana, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPalavraRomajiKatakana, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
       Tela_Sair_Confirma.setContexto(5);
    	new Tela_Sair_Confirma().main(null);
       this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonPalavraHiraganaRomajiActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonPalavraHiraganaRomajiActionPerformed
        Tela_Mensagem.setContexto("h2r_i");
    	Tela_Mensagem.setMensagem("Nessa atividade você deve escrever em       romaji as palavras apresentadas");
    	new Tela_Mensagem().main(null);
        this.dispose();
    }//GEN-LAST:event_jButtonPalavraHiraganaRomajiActionPerformed

    private void jButtonPalavraKatakanaRomajiActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonPalavraKatakanaRomajiActionPerformed
    	Tela_Mensagem.setContexto("k2r_i");
    	Tela_Mensagem.setMensagem("Nessa atividade você deve escrever em       romaji as palavras apresentadas");
    	new Tela_Mensagem().main(null);
    	this.dispose();
    }//GEN-LAST:event_jButtonPalavraKatakanaRomajiActionPerformed

    private void jButtonPalavraRomajiHiraganaActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonPalavraRomajiHiraganaActionPerformed
    	Tela_Intermediario_Converter_2.setContexto("r2h");
    	new Tela_Intermediario_Converter_2().main(null);
    	this.dispose();
    }//GEN-LAST:event_jButtonPalavraRomajiHiraganaActionPerformed

    private void jButtonPalavraRomajiKatakanaActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonPalavraRomajiKatakanaActionPerformed
    	Tela_Intermediario_Converter_2.setContexto("r2k");
    	new Tela_Intermediario_Converter_2().main(null);
    	this.dispose();
    }//GEN-LAST:event_jButtonPalavraRomajiKatakanaActionPerformed

    private void jButtonPalavraHiraganaRomajiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPalavraHiraganaRomajiMouseEntered
         jButtonPalavraHiraganaRomaji.setFont(new java.awt.Font("Arial", 2, 25));
    }//GEN-LAST:event_jButtonPalavraHiraganaRomajiMouseEntered

    private void jButtonPalavraHiraganaRomajiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPalavraHiraganaRomajiMouseExited
        jButtonPalavraHiraganaRomaji.setFont(new java.awt.Font("Goudy Old Style", 2, 30));
    }//GEN-LAST:event_jButtonPalavraHiraganaRomajiMouseExited

    private void jButtonPalavraKatakanaRomajiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPalavraKatakanaRomajiMouseEntered
         jButtonPalavraKatakanaRomaji.setFont(new java.awt.Font("Arial", 2, 25));
    }//GEN-LAST:event_jButtonPalavraKatakanaRomajiMouseEntered

    private void jButtonPalavraKatakanaRomajiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPalavraKatakanaRomajiMouseExited
        jButtonPalavraKatakanaRomaji.setFont(new java.awt.Font("Goudy Old Style", 2, 30));
    }//GEN-LAST:event_jButtonPalavraKatakanaRomajiMouseExited

    private void jButtonPalavraRomajiHiraganaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPalavraRomajiHiraganaMouseEntered
         jButtonPalavraRomajiHiragana.setFont(new java.awt.Font("Arial", 2, 25));
    }//GEN-LAST:event_jButtonPalavraRomajiHiraganaMouseEntered

    private void jButtonPalavraRomajiHiraganaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPalavraRomajiHiraganaMouseExited
        jButtonPalavraRomajiHiragana.setFont(new java.awt.Font("Goudy Old Style", 2, 30));
    }//GEN-LAST:event_jButtonPalavraRomajiHiraganaMouseExited

    private void jButtonPalavraRomajiKatakanaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPalavraRomajiKatakanaMouseEntered
        jButtonPalavraRomajiKatakana.setFont(new java.awt.Font("Arial", 2, 25));
    }//GEN-LAST:event_jButtonPalavraRomajiKatakanaMouseEntered

    private void jButtonPalavraRomajiKatakanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPalavraRomajiKatakanaMouseExited
        jButtonPalavraRomajiKatakana.setFont(new java.awt.Font("Goudy Old Style", 2, 30));
    }//GEN-LAST:event_jButtonPalavraRomajiKatakanaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Intermediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Intermediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Intermediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Intermediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Intermediario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPalavraHiraganaRomaji;
    private javax.swing.JButton jButtonPalavraKatakanaRomaji;
    private javax.swing.JButton jButtonPalavraRomajiHiragana;
    private javax.swing.JButton jButtonPalavraRomajiKatakana;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
