/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.japones.pratice.view;

import java.awt.Color;
import java.awt.font.TextAttribute;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.SwingConstants;

import com.japones.pratice.model.Caractere;

/**
 *
 * @author Suporte TI
 */
public class Tela_Mensagem extends javax.swing.JFrame {

    /**
     * Creates new form Tela_3
     */
	
	
	private static String contexto = "";
	private static boolean praticar_tudo = false;
	private static String mensagem="";
	private static String tipo_atividade = "h";
	

	
	
	
	
	public static void setContexto(String s) {
		contexto = s;
		
	}

	
	public static void setMensagem(String s) {
		mensagem = s;
	}
    public Tela_Mensagem() {
        initComponents();
        getContentPane().setBackground(new Color(255, 170, 170));
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	praticar_tudo = Tela_Iniciante_Escolher_Exercicio.getPraticarTudo();
    	tipo_atividade = Tela_Iniciante_Escolher_Treino.getTipoTreino();

        jButtonVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMensagem = new javax.swing.JTextArea();
        jButtonProximo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 170, 170));

        jButtonVoltar.setIcon(new javax.swing.ImageIcon("src/Imagens/btn_voltar.png")); // NOI18N
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonVoltarActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jScrollPane1.setBackground(new Color(0,0,0,0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setOpaque(false);

        jTextAreaMensagem.setEditable(false);
        jTextAreaMensagem.setBackground(new java.awt.Color(255, 170, 170));
        jTextAreaMensagem.setColumns(2);
        jTextAreaMensagem.setFont(new java.awt.Font("Calibri", 1, 45)); // NOI18N
        jTextAreaMensagem.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaMensagem.setLineWrap(true);
        jTextAreaMensagem.setRows(2);
        jTextAreaMensagem.setText(mensagem);
        jTextAreaMensagem.setWrapStyleWord(true);
        jTextAreaMensagem.setOpaque(false);
        jScrollPane1.setViewportView(jTextAreaMensagem);

        jButtonProximo.setBackground(new java.awt.Color(255, 252, 255));
        jButtonProximo.setFont(new java.awt.Font("Goudy Old Style", 2, 30)); // NOI18N
        jButtonProximo.setForeground(new java.awt.Color(255, 155, 155));
        jButtonProximo.setText("Próximo");
        jButtonProximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonProximoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonProximoMouseExited(evt);
            }
        });
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonProximoActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButtonVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonVoltarActionPerformed
        if(!praticar_tudo)
        	new Tela_Iniciante_Escolher_Exercicio().main(null);
        else {
        	switch (contexto) {
				case "tre_t": 
					Tela_Iniciante_Treino_Revisao_Escrita.setContexto("t");
					new Tela_Iniciante_Treino_Revisao_Escrita().main(null);
					break;
				
				case "tre_r":
					Tela_Iniciante_Treino_Revisao_Escrita.setContexto("r");
					new Tela_Iniciante_Treino_Revisao_Escrita().main(null);
					break;
					
				case "trl_t":
					Tela_Iniciante_Treino_Revisao_Leitura.setContexto("t");
					new Tela_Iniciante_Treino_Revisao_Leitura().main(null);
					break;
					
				case "trl_r":
					Tela_Iniciante_Treino_Revisao_Leitura.setContexto("r");
					new Tela_Iniciante_Treino_Revisao_Leitura().main(null);
					break;
					
				case "r2h", "r2k":
					Tela_Iniciante_Converter.setContexto(contexto);
					new Tela_Iniciante_Converter().main(null);
					break;
					
				case "h2r", "k2r":
					
					Tela_Iniciante_Converter.setContexto(contexto);
					new Tela_Iniciante_Converter().main(null);
					break;
					
				case "h2r_i", "k2r_i":
					new Tela_Intermediario_Converter().main(null);
					break;
			}
        }
        	
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonProximoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProximoMouseEntered
    	 jButtonProximo.setFont(new java.awt.Font("Arial", 2, 25));
    }//GEN-LAST:event_jButtonProximoMouseEntered

    private void jButtonProximoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProximoMouseExited
    	 jButtonProximo.setFont(new java.awt.Font("Goudy Old Style", 2, 30));
    }//GEN-LAST:event_jButtonProximoMouseExited

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonProximoActionPerformed
    	  if(!praticar_tudo && !contexto.equals("h2r_i") && !contexto.equals("k2r_i"))
          	new Tela_Iniciante_Escolher_Exercicio().main(null);
    	  else {
    	switch (contexto) {
			case "tre_t": 
				Tela_Iniciante_Treino_Revisao_Leitura.setContexto("t");
				new Tela_Iniciante_Treino_Revisao_Leitura().main(null);
				break;
			
			case "tre_r":
				Tela_Iniciante_Treino_Revisao_Leitura.setContexto("r");
				new Tela_Iniciante_Treino_Revisao_Leitura().main(null);
				break;
				
			case "trl_t":
				Tela_Iniciante_Treino_Revisao_Escrita.setContexto("r");
				new Tela_Iniciante_Treino_Revisao_Escrita().main(null);
				break;
				
			case "trl_r":
				Tela_Iniciante_Converter.setContexto("r2" + tipo_atividade);
				new Tela_Iniciante_Converter().main(null);
				break;
				
			case "r2h", "r2k":
				Tela_Iniciante_Converter.setContexto(tipo_atividade + "2r");
				new Tela_Iniciante_Converter().main(null);
				break;
				
			case "h2r", "k2r":
				Tela_Iniciante_Converter.setContexto(tipo_atividade + "2r");
				new Tela_Iniciante_Converter().main(null);
				break;
				
				
			case "h2r_i":
				Tela_Intermediario_Converter.setContexto("h2r");
		        new Tela_Intermediario_Converter().main(null);
		        break;
		        
			case "k2r_i":
				Tela_Intermediario_Converter.setContexto("k2r");
		        new Tela_Intermediario_Converter().main(null);
				break;
	
				
			
		}
    	  }
    	  
    	  this.dispose();
    }//GEN-LAST:event_jButtonProximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Mensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Mensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Mensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Mensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Mensagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMensagem;
    // End of variables declaration//GEN-END:variables
}
