/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.japones.pratice.view;

import java.awt.Color;
import java.awt.font.TextAttribute;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Suporte TI
 */
public class Tela_Iniciante_Escolher_Treino extends javax.swing.JFrame {

    /**
     * Creates new form Tela_3
     */
	
	private static String tipo_treino = "h";
	
	public static String getTipoTreino() {
		return tipo_treino;
	}
    public Tela_Iniciante_Escolher_Treino() {
        initComponents();
        getContentPane().setBackground(new Color(255, 170, 170));
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonHiragana = new javax.swing.JButton();
        jButtonKatakana = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 170, 170));

        jScrollPane1.setBackground(new Color(0,0,0,0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setOpaque(false);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 170, 170));
        jTextArea1.setColumns(2);
        jTextArea1.setFont(new java.awt.Font("Calibri", 1, 60)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(2);
        jTextArea1.setText(" Bem vindo(a), Sakura! O que       gostaria de treinar hoje?");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonHiragana.setBackground(new java.awt.Color(255, 252, 255));
        jButtonHiragana.setFont(new java.awt.Font("Goudy Old Style", 2, 30)); // NOI18N
        jButtonHiragana.setForeground(new java.awt.Color(255, 155, 155));
        jButtonHiragana.setText("Hiragana");
        jButtonHiragana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonHiraganaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonHiraganaMouseExited(evt);
            }
        });
        jButtonHiragana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHiraganaActionPerformed(evt);
            }
        });

        jButtonKatakana.setBackground(new java.awt.Color(255, 252, 255));
        jButtonKatakana.setFont(new java.awt.Font("Goudy Old Style", 2, 30)); // NOI18N
        jButtonKatakana.setForeground(new java.awt.Color(255, 155, 155));
        jButtonKatakana.setText("Katakana");
        jButtonKatakana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonKatakanaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonKatakanaMouseExited(evt);
            }
        });
        jButtonKatakana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKatakanaActionPerformed(evt);
            }
        });

        jButtonSair.setBackground(new Color(0,0,0,0));
        jButtonSair.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSair.setText("Sair");
        jButtonSair.setContentAreaFilled(false);
        jButtonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSairMouseExited(evt);
            }
        });
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButtonSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonHiragana, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jButtonKatakana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonHiragana, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonKatakana, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKatakanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKatakanaActionPerformed
    	

    	tipo_treino = "k";
         new Tela_Iniciante_Escolher_Atividade().main(null);
         this.dispose();
    }//GEN-LAST:event_jButtonKatakanaActionPerformed

    private void jButtonHiraganaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHiraganaActionPerformed
     
    	tipo_treino = "h";
        new Tela_Iniciante_Escolher_Atividade().main(null);
        this.dispose();
    }//GEN-LAST:event_jButtonHiraganaActionPerformed

    private void jButtonHiraganaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHiraganaMouseEntered
       jButtonHiragana.setFont(new java.awt.Font("Arial", 2, 30));
    }//GEN-LAST:event_jButtonHiraganaMouseEntered

    private void jButtonHiraganaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHiraganaMouseExited
        jButtonHiragana.setFont(new java.awt.Font("Goudy Old Style", 2, 30));
    }//GEN-LAST:event_jButtonHiraganaMouseExited

    private void jButtonKatakanaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKatakanaMouseEntered
        jButtonKatakana.setFont(new java.awt.Font("Arial", 2, 30));
    }//GEN-LAST:event_jButtonKatakanaMouseEntered

    private void jButtonKatakanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKatakanaMouseExited
       jButtonKatakana.setFont(new java.awt.Font("Goudy Old Style", 2, 30));
    }//GEN-LAST:event_jButtonKatakanaMouseExited

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        Tela_Sair_Confirma.setContexto(0);
        new Tela_Sair_Confirma().main(null);
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseEntered
       Map<TextAttribute, Object> atributos = new HashMap<TextAttribute, Object>();
atributos.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
       jButtonSair.setFont(new java.awt.Font("Calibri", 1, 30).deriveFont(atributos)); 
    }//GEN-LAST:event_jButtonSairMouseEntered

    private void jButtonSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseExited
        jButtonSair.setFont(new java.awt.Font("Calibri", 0, 30)); 
    }//GEN-LAST:event_jButtonSairMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Iniciante_Escolher_Treino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Iniciante_Escolher_Treino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Iniciante_Escolher_Treino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Iniciante_Escolher_Treino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Iniciante_Escolher_Treino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHiragana;
    private javax.swing.JButton jButtonKatakana;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
