/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.japones.pratice.view;

import java.awt.Color;
import java.awt.font.TextAttribute;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.SwingConstants;

import com.japones.pratice.controller.Controller;
import com.japones.pratice.model.Caractere;

/**
 *
 * @author Suporte TI
 */
public class Tela_Iniciante_Treino_Revisao_Escrita extends javax.swing.JFrame {

    /**
     * Creates new form Tela_3
     */
	
	private static ArrayList<Caractere> lista;
	private static String tipo_atividade = "h";
	private static String treino_revisao = "t";
	private static boolean praticar_tudo = false;
	private static Connection conexao = Tela_Inicial.getConexao();
	private static int atividade = 1;
	

	
	
	
	public static void setContexto(String s) {
		treino_revisao = s;
		
	}

	public static void setLista(ArrayList<Caractere> al) {
		lista = al;
	}


	
	
    public Tela_Iniciante_Treino_Revisao_Escrita() throws SQLException {
        initComponents();
        getContentPane().setBackground(new Color(255, 170, 170));
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws SQLException 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws SQLException {

    	atividade = Tela_Iniciante_Escolher_Atividade.getAtividade();
    	praticar_tudo = Tela_Iniciante_Escolher_Exercicio.getPraticarTudo();
    	tipo_atividade = Tela_Iniciante_Escolher_Treino.getTipoTreino();
    	
    	jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMensagem = new javax.swing.JTextArea();
        jButtonTerminei = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaTexto = new javax.swing.JTextArea();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 170, 170));

        jScrollPane1.setBackground(new Color(0,0,0,0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setOpaque(false);

        jTextAreaMensagem.setEditable(false);
        jTextAreaMensagem.setBackground(new java.awt.Color(255, 170, 170));
        jTextAreaMensagem.setColumns(2);
        jTextAreaMensagem.setFont(new java.awt.Font("Calibri", 1, 45)); // NOI18N
        jTextAreaMensagem.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaMensagem.setLineWrap(true);
        jTextAreaMensagem.setRows(2);
        String treino ="";
    	if(tipo_atividade.equals("h"))
    		treino = "hiragana";
    	else
    		treino ="katakana";
    	
        jTextAreaMensagem.setText("    Em um caderno escreva o seguinte " + treino + " pelo menos 15 vezes. Quando          finalizar clique em \"terminei\".");
        jTextAreaMensagem.setWrapStyleWord(true);
        jTextAreaMensagem.setOpaque(false);
        jScrollPane1.setViewportView(jTextAreaMensagem);

        jButtonTerminei.setBackground(new java.awt.Color(255, 252, 255));
        jButtonTerminei.setFont(new java.awt.Font("Goudy Old Style", 2, 30)); // NOI18N
        jButtonTerminei.setForeground(new java.awt.Color(255, 155, 155));
        jButtonTerminei.setText("Terminei");
        jButtonTerminei.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonTermineiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonTermineiMouseExited(evt);
            }
        });
        jButtonTerminei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTermineiActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new Color(0,0,0,0));
        jScrollPane2.setBorder(null);
        jScrollPane2.setEnabled(false);
        jScrollPane2.setOpaque(false);

        jTextAreaTexto.setEditable(false);
        jTextAreaTexto.setBackground(new java.awt.Color(255, 170, 170));
        jTextAreaTexto.setColumns(2);
        jTextAreaTexto.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 45)); // NOI18N
        jTextAreaTexto.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaTexto.setLineWrap(true);
        jTextAreaTexto.setRows(2);
        jTextAreaTexto.setText(pegarCaracteres());
        jTextAreaTexto.setWrapStyleWord(true);
        jTextAreaTexto.setOpaque(false);
        jScrollPane2.setViewportView(jTextAreaTexto);
        
        jButtonSair.setBackground(new Color(0,0,0,0));
        jButtonSair.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(255, 255, 255));
        String nome = "";
        if(treino_revisao.equals("t"))
        	nome = "Sair";
        jButtonSair.setText("Sair");
        jButtonSair.setContentAreaFilled(false);
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonSairActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jButtonSair)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTerminei, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(50, 50, 50))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(50, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addGap(23, 23, 23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonTerminei, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSair))
                    .addGap(44, 44, 44))
            );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTermineiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTermineiActionPerformed
        if (!praticar_tudo)
        	new Tela_Iniciante_Escolher_Exercicio().main(null);
        else {
        	
        		String treino ="";
            	if(tipo_atividade.equals("h"))
            		treino = "hiragana";
            	else
            		treino ="katakana";
            	
            	if(treino_revisao.equals("t")) {
            	Tela_Mensagem.setMensagem("Nessa atividade você terá a missão de          identificar qual é o romaji que             corresponde ao " + treino + "  mostrado.");
            	Tela_Mensagem.setContexto("tre_t");
            	}
            	else {
            		Tela_Mensagem.setMensagem(" Nessa atividade iremos trabalhar com    todos " + treino + " aprendidos até agora");
            		Tela_Mensagem.setContexto("tre_r");
            	}
            	new Tela_Mensagem().main(null);
        	
        }
        	
        
        this.dispose();
    }//GEN-LAST:event_jButtonTermineiActionPerformed

    private void jButtonTermineiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTermineiMouseEntered
    	jButtonTerminei.setFont(new java.awt.Font("Arial", 2, 30));
    }//GEN-LAST:event_jButtonTermineiMouseEntered

    private void jButtonTermineiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTermineiMouseExited
    	jButtonTerminei.setFont(new java.awt.Font("Goudy Old Style", 2, 30));
    }//GEN-LAST:event_jButtonTermineiMouseExited
    
    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {// GEN-FIRST:event_jButtonSairActionPerformed
		if(treino_revisao.equals("r") && praticar_tudo) {
			Tela_Iniciante_Treino_Revisao_Leitura.setContexto("t");
			new Tela_Iniciante_Treino_Revisao_Leitura().main(null);
		}
		else {
    	Tela_Sair_Confirma.setContexto(2);
		new Tela_Sair_Confirma().main(null);
		}
		this.dispose();

	}// GEN-LAST:event_jButtonSairActionPerformed

	private void jButtonSairMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButtonSairMouseEntered
		Map<TextAttribute, Object> atributos = new HashMap<TextAttribute, Object>();
		atributos.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
		jButtonSair.setFont(new java.awt.Font("Calibri", 1, 30).deriveFont(atributos));
	}// GEN-LAST:event_jButtonSairMouseEntered

	private void jButtonSairMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButtonSairMouseExited
		jButtonSair.setFont(new java.awt.Font("Calibri", 0, 30));
	}// GEN-LAST:event_jButtonSairMouseExited
    
    private String pegarCaracteres() throws SQLException{
    	Controller controller = new Controller();
    	if(treino_revisao.equals("t")) 
    		lista = controller.pegarAtividade(atividade, conexao).getCaractere();
    	else
    		lista = controller.pegarRevisao(atividade, conexao);
    	
    	String caracteres = "";
    	
    	for(Caractere c: lista) {
    		if(tipo_atividade.equals("h"))
    			caracteres = caracteres + c.getHiragana() + " ";
    			else
    				caracteres = caracteres + c.getKatakana() + " ";
    	}
    	
    	return caracteres;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Iniciante_Treino_Revisao_Escrita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Iniciante_Treino_Revisao_Escrita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Iniciante_Treino_Revisao_Escrita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Iniciante_Treino_Revisao_Escrita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new Tela_Iniciante_Treino_Revisao_Escrita().setVisible(true);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonTerminei;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaMensagem;
    private javax.swing.JTextArea jTextAreaTexto;
    // End of variables declaration//GEN-END:variables
}
